### ISSUE TITLE
Update Conversions table

### ISSUE THREAD

**Issue by OpenOilUG** [fossilfuelregistry/portal#106]
[conversion_constant_updated_211031.csv](https://github.com/fossilfuelregistry/portal/files/7449301/conversion_constant_updated_211031.csv)Values for coal combustion emissions have been updated to P5 low and P95 high (instead of P10 low and P90 high). Values have been changed all other data left the same.

**Comment by OpenOilUG** [comment]
[conversion_constant_updated_211031.csv](https://github.com/fossilfuelregistry/portal/files/7449301/conversion_constant_updated_211031.csv)Values for coal combustion emissions have been updated to P5 low and P95 high (instead of P10 low and P90 high). Values have been changed all other data left the same.

**Comment by JesperWe** [comment]
Ingested
