### ISSUE TITLE
Protect graphs against browsers in dark mode.

### ISSUE THREAD

**Issue by frank-calma** [fossilfuelregistry/portal#108]
CO2 Forecast PNG download background is too dark, which makes it difficult to see the text of the x and y axes (e.g. M ton CO2e, Year). See attached image. 

![CO2Forecast](https://user-images.githubusercontent.com/6556555/139595145-70414167-3f30-4788-a6d2-43212c449285.png)

**Comment by JesperWe** [comment]
I cannot reproduce any issues. I believe this was Franks issues were caused by his environment.
