### ISSUE TITLE
Integrate Opgee oil upstream country-specific conversion numbers

### ISSUE THREAD

**Issue by JesperWe** [fossilfuelregistry/portal#2]
Make conversion table units have modifiers:

- [ ] country
- [ ] scope
- [ ] project
- [ ] Authority level

**Comment by OpenOilUG** [comment]
Here is latest thinking on conversion table my side as displayed in convo 7.5: cells marked in yellow are updates either of value in existing records or new records, marked in red are suggested deletions. note significant changes to range values within existing entries which must be updated (separate to question of implementation of country level Opgee scope 1 and 2 estimates). 
[conversion_constant_210108_1355.xlsx](https://github.com/JesperWe/grff-portal/files/6445798/conversion_constant_210108_1355.xlsx)

**Comment by OpenOilUG** [comment]
This is now subsumed into Issue #20
