### ISSUE TITLE
Integrate two sample sets of project data

### ISSUE THREAD

**Issue by OpenOilUG** [fossilfuelregistry/portal#24]

**Comment by OpenOilUG** [comment]
Denmark and Mexico. Data are already processed. Two stages:

1) Accommodation of project-based production and reserves.
2) Correct uploading of Mexico and Denmark data.
3) Adaptation of Paradigm used at country level to project-level
4) Project-aggregator page by country (to be linked to off the country page itself)

**Comment by OpenOilUG** [comment]
Currently not integrating reserves at project level in the same way as happens at country level. For instance https://dev.fossilfuelregistry.org/co2-forecast?country=mx&project=Abkatun&productionSourceId=7&projectionSourceId=100

**Comment by JesperWe** [comment]
@OpenOilUG There seems to be some unit problem. Gas production is on the order of 5000 X the reserves?

**Comment by JesperWe** [comment]
@OpenOilUG also good if you can exclude "condensate" sources since it has no support.
