### ISSUE TITLE
Investigate raw data storage approach

### ISSUE THREAD

**Issue by OpenOilUG** [fossilfuelregistry/portal#25]

**Comment by OpenOilUG** [comment]
The Registry should host copies of all raw data used to compile country and field-level estimates. Estimated space need: 10GB to 100GB. Solution should be sustainable (either within Github or a hosting service which is costed to be affordable indefinitely)

**Comment by JesperWe** [comment]
@OpenOilUG I spent some time looking at existing solutions to integrate a file browser from the DigitalOcean storage into the site, but found nothing that would give us a workable solution without significant effort.

I would suggest CTI opening a separate Google Drive Enterprise account (It's just $8/month) in the FossilFuelRegistry name, where we publicise a folder with all your stuff underneath.
