### ISSUE TITLE
Create a cleaned up set of production data for all producing countries.

### ISSUE THREAD

**Issue by JesperWe** [fossilfuelregistry/portal#3]

**Comment by OpenOilUG** [comment]
I believe attached is cleaned version in xls but you need to check conversion into csv. Two versions, one with and one without null and negative values.__
[country_production_210507_1758_jw.xlsx](https://github.com/JesperWe/grff-portal/files/6445471/country_production_210507_1758_jw.xlsx)
[country_production_POS_210507_1800_jw.xlsx](https://github.com/JesperWe/grff-portal/files/6445472/country_production_POS_210507_1800_jw.xlsx)
