### ISSUE TITLE
Add translations of country names for non-english users

### ISSUE THREAD

**Issue by JesperWe** [fossilfuelregistry/portal#30]
Data from https://stefangabos.github.io/world_countries/

**Comment by OpenOilUG** [comment]
on French...
Arabie Saoudite (capped)
Emirats Arabes Unis (capped)
Guinea Equitoriale
Republique Democratique de Congo
Timor Oriental

**Comment by JesperWe** [comment]
> on French...
> Arabie Saoudite (capped)
> Emirats Arabes Unis (capped)
> Guinea Equitoriale
> Republique Democratique de Congo
> Timor Oriental

Fixed
