### ISSUE TITLE
Danish project data projection has wrong units.

### ISSUE THREAD

**Issue by JesperWe** [fossilfuelregistry/portal#37]
Projected volumes are 1000x historic.

Manually fixed for Halfdan project just to verify #34

**Comment by OpenOilUG** [comment]
I believe this is fixed: project-level projection units altered in oil from e6m3 to e3m3 and in gas from e9m3 to e6m3. 
[country_production_20210820_issue37bugfix.csv](https://github.com/fossilfuelregistry/portal/files/7020953/country_production_20210820_issue37bugfix.csv)
