### ISSUE TITLE
Some Sparse Projects Not Displaying

### ISSUE THREAD

**Issue by OpenOilUG** [fossilfuelregistry/portal#49]

**Comment by OpenOilUG** [comment]
E.g. GEM coal file normalised for ingestion has three producing coal mines but none show up on the Turkey country page. https://dev.fossilfuelregistry.org/co2-forecast/tr?

I suspect other coal projects are also not showing - it seems unusual to me that India's top 10 emitting projects all appear to be oil and gas.

In the UK one sparse project turns up which is an oil and gas project and carries a GEM OGF code.. But the policy is not to include sparse projects for any fossil fuel / jurisdiction combination for which we have dense data, which is the case in the UK. So am wondering about which data got ingested for Sparse data set.

**Comment by JesperWe** [comment]
Fixed in backend sparse import

**Comment by OpenOilUG** [comment]
Similar issues to Turkey:

- https://dev.fossilfuelregistry.org/co2-forecast/pl?

**Comment by JesperWe** [comment]
pl and zw have no projects in GEM files.

**Comment by OpenOilUG** [comment]
ah. identified 3166 error. if you update all iso3166=zm to iso3166=zw and iso3166=po to iso3166=pl that should fix it.
