### ISSUE TITLE
Mexico: Suspected units issue for dense projects

### ISSUE THREAD

**Issue by JesperWe** [fossilfuelregistry/portal#51]
Example: Agua Fria Gas production 100 e9m3, reserves 5 e9m3

**Comment by OpenOilUG** [comment]
Identified: all gas production and projections should be in e6feet3 as opposed to now where some are e6feet3 and most are e9feet3. as per file attached.
[dense_projects_202108301140_valid.csv](https://github.com/fossilfuelregistry/portal/files/7076030/dense_projects_202108301140_valid.csv)
