### ISSUE TITLE
Project site names missing from Largest Emissions Projects selector

### ISSUE THREAD

**Issue by frank-calma** [fossilfuelregistry/portal#89]
Seems to be fairly prevalent across different countries. Coal projects don't seem to be effected, but oil and gas projects are lacking text and searchability (when using the text search).

<img width="440" alt="Screenshot 2021-10-30 at 15 41 41" src="https://user-images.githubusercontent.com/6556555/139535104-2c2566cf-b485-473c-b57d-fa386cfe2911.png">

**Comment by JesperWe** [comment]
Fixed after GEM oil/gas reimport
